/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/admin-items-of-wishlist-api';
export * from './apis/admin-popular-products-api';
export * from './apis/admin-promotional-email-api';
export * from './apis/admin-wccoupons-api';
export * from './apis/admin-wishlists-api';
export * from './apis/items-of-wishlist-api';
export * from './apis/settings-api';
export * from './apis/wishlists-api';

