/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddToCart
 */
export interface AddToCart {
    /**
     * 
     * @type {string}
     * @memberof AddToCart
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof AddToCart
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddToCart
     */
    requiresSelection?: boolean;
}
