/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdminGetWishlistsElement } from './admin-get-wishlists-element';
/**
 * 
 * @export
 * @interface AdminGetWishlistsResponse
 */
export interface AdminGetWishlistsResponse {
    /**
     * AdminGetWishlistsElement>
     * @type {Array<AdminGetWishlistsElement>}
     * @memberof AdminGetWishlistsResponse
     */
    items?: Array<AdminGetWishlistsElement>;
    /**
     * 
     * @type {number}
     * @memberof AdminGetWishlistsResponse
     */
    total?: number;
}
