/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BulkActionMessage
 */
export interface BulkActionMessage {
    /**
     * 
     * @type {string}
     * @memberof BulkActionMessage
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof BulkActionMessage
     */
    entityId?: number;
    /**
     * 
     * @type {string}
     * @memberof BulkActionMessage
     */
    entityTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkActionMessage
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof BulkActionMessage
     */
    message?: string;
}
