/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CategoryOfPopularItem
 */
export interface CategoryOfPopularItem {
    /**
     * 
     * @type {number}
     * @memberof CategoryOfPopularItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryOfPopularItem
     */
    name?: string;
}
