/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BulkActionMessage } from './bulk-action-message';
import { ExtendedItemOfWishlist } from './extended-item-of-wishlist';
/**
 * 
 * @export
 * @interface ExecuteActionsOnItemsOfWishlistResponse
 */
export interface ExecuteActionsOnItemsOfWishlistResponse {
    /**
     * BulkActionMessage|Error>
     * @type {Array<BulkActionMessage>}
     * @memberof ExecuteActionsOnItemsOfWishlistResponse
     */
    messages?: Array<BulkActionMessage>;
    /**
     * 
     * @type {Array<ExtendedItemOfWishlist>}
     * @memberof ExecuteActionsOnItemsOfWishlistResponse
     */
    newItems?: Array<ExtendedItemOfWishlist>;
}
