/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExecuteActionsOnItemsOfWishlistRequest
 */
export interface ExecuteActionsOnItemsOfWishlistRequest {
    /**
     * 
     * @type {string}
     * @memberof ExecuteActionsOnItemsOfWishlistRequest
     */
    action?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ExecuteActionsOnItemsOfWishlistRequest
     */
    itemIds?: Array<number>;
    /**
     * 
     * @type {any}
     * @memberof ExecuteActionsOnItemsOfWishlistRequest
     */
    options?: any;
}
