/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddToCart } from './add-to-cart';
import { Price } from './price';
import { Stock } from './stock';
import { Thumbnail } from './thumbnail';
/**
 * 
 * @export
 * @interface ExtendedItemOfWishlist
 */
export interface ExtendedItemOfWishlist {
    /**
     * 
     * @type {number}
     * @memberof ExtendedItemOfWishlist
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedItemOfWishlist
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedItemOfWishlist
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof ExtendedItemOfWishlist
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedItemOfWishlist
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedItemOfWishlist
     */
    virtualProduct?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedItemOfWishlist
     */
    downloadable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExtendedItemOfWishlist
     */
    sku?: string;
    /**
     * 
     * @type {number}
     * @memberof ExtendedItemOfWishlist
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedItemOfWishlist
     */
    priority?: number;
    /**
     * 
     * @type {any}
     * @memberof ExtendedItemOfWishlist
     */
    variation?: any;
    /**
     * 
     * @type {any}
     * @memberof ExtendedItemOfWishlist
     */
    cartItemData?: any;
    /**
     * 
     * @type {string}
     * @memberof ExtendedItemOfWishlist
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedItemOfWishlist
     */
    permalink?: string;
    /**
     * 
     * @type {Thumbnail}
     * @memberof ExtendedItemOfWishlist
     */
    thumbnail?: Thumbnail;
    /**
     * 
     * @type {Stock}
     * @memberof ExtendedItemOfWishlist
     */
    stock?: Stock;
    /**
     * 
     * @type {Price}
     * @memberof ExtendedItemOfWishlist
     */
    price?: Price;
    /**
     * 
     * @type {AddToCart}
     * @memberof ExtendedItemOfWishlist
     */
    addToCart?: AddToCart;
}
