/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { Sorting } from './sorting';
/**
 * 
 * @export
 * @interface GetUsersOfPopularItemRequest
 */
export interface GetUsersOfPopularItemRequest {
    /**
     * 
     * @type {number}
     * @memberof GetUsersOfPopularItemRequest
     */
    productId?: number;
    /**
     * 
     * @type {any}
     * @memberof GetUsersOfPopularItemRequest
     */
    variation?: any;
    /**
     * 
     * @type {Pagination}
     * @memberof GetUsersOfPopularItemRequest
     */
    pagination?: Pagination;
    /**
     * Sorting>
     * @type {Array<Sorting>}
     * @memberof GetUsersOfPopularItemRequest
     */
    sorting?: Array<Sorting>;
}
