/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ItemOfWishlistRequest
 */
export interface ItemOfWishlistRequest {
    /**
     * 
     * @type {number}
     * @memberof ItemOfWishlistRequest
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemOfWishlistRequest
     */
    wishlistId?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemOfWishlistRequest
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemOfWishlistRequest
     */
    quantity?: number;
    /**
     * 
     * @type {any}
     * @memberof ItemOfWishlistRequest
     */
    variation?: any;
    /**
     * 
     * @type {any}
     * @memberof ItemOfWishlistRequest
     */
    cartItemData?: any;
    /**
     * 
     * @type {number}
     * @memberof ItemOfWishlistRequest
     */
    priority?: number;
}
