/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OptionSelections
 */
export interface OptionSelections {
    /**
     * 
     * @type {string}
     * @memberof OptionSelections
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionSelections
     */
    value?: string;
}
