/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelObject } from './model-object';
import { OptionSelections } from './option-selections';
/**
 * 
 * @export
 * @interface Option
 */
export interface Option {
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Option
     */
    title?: string;
    /**
     * 
     * @type {ModelObject}
     * @memberof Option
     */
    defaultValue?: ModelObject;
    /**
     * 
     * @type {ModelObject}
     * @memberof Option
     */
    value?: ModelObject;
    /**
     * 
     * @type {Array<OptionSelections>}
     * @memberof Option
     */
    selections?: Array<OptionSelections>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Option
     */
    customizeUrls?: Array<any>;
}
