/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryOfPopularItem } from './category-of-popular-item';
/**
 * 
 * @export
 * @interface PopularItem
 */
export interface PopularItem {
    /**
     * 
     * @type {number}
     * @memberof PopularItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PopularItem
     */
    title?: string;
    /**
     * 
     * @type {any}
     * @memberof PopularItem
     */
    variation?: any;
    /**
     * 
     * @type {any}
     * @memberof PopularItem
     */
    cartItemData?: any;
    /**
     * 
     * @type {Array<CategoryOfPopularItem>}
     * @memberof PopularItem
     */
    categories?: Array<CategoryOfPopularItem>;
    /**
     * 
     * @type {number}
     * @memberof PopularItem
     */
    totalCount?: number;
    /**
     * 
     * @type {string}
     * @memberof PopularItem
     */
    link?: string;
}
