/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    unitPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    minPrice?: string;
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    minPriceValue?: number;
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    maxPrice?: string;
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    maxPriceValue?: number;
    /**
     * 
     * @type {string}
     * @memberof Price
     */
    priceHtml?: string;
}
