/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';
/**
 * 
 * @export
 * @interface PromotionalEmailCalculateEmailReceiversRequest
 */
export interface PromotionalEmailCalculateEmailReceiversRequest {
    /**
     * Product>
     * @type {Array<Product>}
     * @memberof PromotionalEmailCalculateEmailReceiversRequest
     */
    products?: Array<Product>;
    /**
     * int>
     * @type {Array<number>}
     * @memberof PromotionalEmailCalculateEmailReceiversRequest
     */
    userIds?: Array<number>;
}
