/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';
/**
 * 
 * @export
 * @interface PromotionalEmailRequest
 */
export interface PromotionalEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof PromotionalEmailRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionalEmailRequest
     */
    htmlContent?: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionalEmailRequest
     */
    plainContent?: string;
    /**
     * Product>
     * @type {Array<Product>}
     * @memberof PromotionalEmailRequest
     */
    products?: Array<Product>;
    /**
     * int>
     * @type {Array<number>}
     * @memberof PromotionalEmailRequest
     */
    userIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof PromotionalEmailRequest
     */
    coupon?: string;
}
