/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StockAvailability
 */
export interface StockAvailability {
    /**
     * 
     * @type {string}
     * @memberof StockAvailability
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof StockAvailability
     */
    stockClass?: string;
}
