/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserOfPopularItem } from './user-of-popular-item';
/**
 * 
 * @export
 * @interface UsersOfPopularItemResponse
 */
export interface UsersOfPopularItemResponse {
    /**
     * UserOfPopularItem>
     * @type {Array<UserOfPopularItem>}
     * @memberof UsersOfPopularItemResponse
     */
    items?: Array<UserOfPopularItem>;
    /**
     * 
     * @type {number}
     * @memberof UsersOfPopularItemResponse
     */
    total?: number;
}
