/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WishlistRequest
 */
export interface WishlistRequest {
    /**
     * 
     * @type {number}
     * @memberof WishlistRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WishlistRequest
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof WishlistRequest
     */
    shareTypeId?: number;
}
