/* tslint:disable */
/* eslint-disable */
/**
 * Algol WC Wishlist
 * Algol WC Wishlist
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetPopularItemsRequest } from '../models';
import { GetUsersOfPopularItemRequest } from '../models';
import { PopularItemsResponse } from '../models';
import { UsersFileBody } from '../models';
import { UsersOfPopularItemResponse } from '../models';
/**
 * AdminPopularProductsApi - axios parameter creator
 * @export
 */
export const AdminPopularProductsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GetPopularItemsRequest} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetPopularProducts: async (body: GetPopularItemsRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling adminGetPopularProducts.');
            }
            const localVarPath = `/admin/wishlists/popular-items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-WP-Nonce")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-WP-Nonce"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetUsersOfPopularItemRequest} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetUsersOfPopularItem: async (body: GetUsersOfPopularItemRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling adminGetUsersOfPopularItem.');
            }
            const localVarPath = `/admin/wishlists/popular-items/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-WP-Nonce")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-WP-Nonce"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UsersFileBody} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminGetUsersOfPopularItemAsFile: async (body: UsersFileBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling adminGetUsersOfPopularItemAsFile.');
            }
            const localVarPath = `/admin/wishlists/popular-items/users/file`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("X-WP-Nonce")
                    : await configuration.apiKey;
                localVarHeaderParameter["X-WP-Nonce"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminPopularProductsApi - functional programming interface
 * @export
 */
export const AdminPopularProductsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GetPopularItemsRequest} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetPopularProducts(body: GetPopularItemsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PopularItemsResponse>>> {
            const localVarAxiosArgs = await AdminPopularProductsApiAxiosParamCreator(configuration).adminGetPopularProducts(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {GetUsersOfPopularItemRequest} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetUsersOfPopularItem(body: GetUsersOfPopularItemRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UsersOfPopularItemResponse>>> {
            const localVarAxiosArgs = await AdminPopularProductsApiAxiosParamCreator(configuration).adminGetUsersOfPopularItem(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {UsersFileBody} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetUsersOfPopularItemAsFile(body: UsersFileBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await AdminPopularProductsApiAxiosParamCreator(configuration).adminGetUsersOfPopularItemAsFile(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AdminPopularProductsApi - factory interface
 * @export
 */
export const AdminPopularProductsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {GetPopularItemsRequest} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetPopularProducts(body: GetPopularItemsRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<PopularItemsResponse>> {
            return AdminPopularProductsApiFp(configuration).adminGetPopularProducts(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GetUsersOfPopularItemRequest} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetUsersOfPopularItem(body: GetUsersOfPopularItemRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<UsersOfPopularItemResponse>> {
            return AdminPopularProductsApiFp(configuration).adminGetUsersOfPopularItem(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UsersFileBody} body Fetch request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminGetUsersOfPopularItemAsFile(body: UsersFileBody, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return AdminPopularProductsApiFp(configuration).adminGetUsersOfPopularItemAsFile(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminPopularProductsApi - object-oriented interface
 * @export
 * @class AdminPopularProductsApi
 * @extends {BaseAPI}
 */
export class AdminPopularProductsApi extends BaseAPI {
    /**
     * 
     * @param {GetPopularItemsRequest} body Fetch request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPopularProductsApi
     */
    public async adminGetPopularProducts(body: GetPopularItemsRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<PopularItemsResponse>> {
        return AdminPopularProductsApiFp(this.configuration).adminGetPopularProducts(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {GetUsersOfPopularItemRequest} body Fetch request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPopularProductsApi
     */
    public async adminGetUsersOfPopularItem(body: GetUsersOfPopularItemRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<UsersOfPopularItemResponse>> {
        return AdminPopularProductsApiFp(this.configuration).adminGetUsersOfPopularItem(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {UsersFileBody} body Fetch request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminPopularProductsApi
     */
    public async adminGetUsersOfPopularItemAsFile(body: UsersFileBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return AdminPopularProductsApiFp(this.configuration).adminGetUsersOfPopularItemAsFile(body, options).then((request) => request(this.axios, this.basePath));
    }
}
